version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    container_name: 'postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_PASSWORD: 'blockscout'
        POSTGRES_DB: blockscout
    ports:
      - 5432:5432
